//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18047
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VfpClient {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VfpClient.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] BlankDbc {
            get {
                object obj = ResourceManager.GetObject("BlankDbc", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] BlankDct {
            get {
                object obj = ResourceManager.GetObject("BlankDct", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] BlankDcx {
            get {
                object obj = ResourceManager.GetObject("BlankDcx", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE CURSOR curOutput(cTableName v(254), cAutoInc v(254), cCandidate v(254))
        ///CREATE CURSOR curTables(cTableName v(254))
        ///{0}
        ///
        ///
        ///USE IN SELECT(&quot;VfpClientAlias&quot;)
        ///SELECT curTables
        ///SCAN
        ///	SELECT 0
        ///	USE (curTables.cTableName) AGAIN ALIAS VfpClientAlias
        ///	
        ///	FOR lnIndex = 1 TO AFIELDS(laFields)
        ///		IF laFields[lnIndex, 18] &gt; 0
        ///			INSERT INTO curOutput VALUES(curTables.cTableName, laFields[lnIndex, 1], &apos;&apos;)
        ///			EXIT
        ///		ENDIF
        ///	NEXT
        ///	
        ///	USE  
        ///ENDSCAN
        ///
        ///DELETE FROM curTables WHERE cTableName IN (SELECT cTa [rest of string was truncated]&quot;;.
        /// </summary>
        public static string IndexSchemaAutoIncCandidate {
            get {
                return ResourceManager.GetString("IndexSchemaAutoIncCandidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USE IN SELECT (&quot;{0}&quot;)
        ///USE {0} IN SELECT (0) EXCLUSIVE
        ///PACK
        ///USE IN SELECT (&quot;{0}&quot;).
        /// </summary>
        public static string PackTable {
            get {
                return ResourceManager.GetString("PackTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this data provider to connect to Visual FoxPro Data..
        /// </summary>
        public static string Provider_Description {
            get {
                return ResourceManager.GetString("Provider_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NET Framework Data Provider for Visual FoxPro Data.
        /// </summary>
        public static string Provider_DisplayName {
            get {
                return ResourceManager.GetString("Provider_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VfpClient.
        /// </summary>
        public static string Provider_ShortDisplayName {
            get {
                return ResourceManager.GetString("Provider_ShortDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE CURSOR curOutput(TableName v(254), FieldName v(254), Caption M, Comment M, DefaultValue M, DisplayClass M, DisplayClassLibrary M, Format M, InputMask M, RuleExpression M, RuleText M, FieldType C)
        ///
        ///LOCAL llIsDbc
        ///
        ///llIsDbc = !EMPTY(DBC())
        ///
        ///CREATE CURSOR curTables(TableName v(254))
        ///{0}
        ///
        ///USE IN SELECT(&quot;VfpClientAlias&quot;)
        ///SELECT curTables
        ///SCAN
        ///	SELECT 0
        ///	USE (curTables.TableName) AGAIN ALIAS VfpClientAlias
        ///	
        ///	FOR lnIndex = 1 TO AFIELDS(laFields)
        ///		lcFieldName = laFields[lnIndex, 1]
        ///		lcTable [rest of string was truncated]&quot;;.
        /// </summary>
        public static string TableFieldProps {
            get {
                return ResourceManager.GetString("TableFieldProps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE CURSOR curOutput(TableName v(254), Comment M, DeleteTrigger M, InsertTrigger M, Path M, PrimaryKey M, RuleExpression M, RuleText M, UpdateTrigger M)
        ///
        ///IF EMPTY(DBC())
        ///	RETURN
        ///ENDIF 
        ///
        ///CREATE CURSOR curTables(TableName v(254))
        ///{0}
        ///
        ///USE IN SELECT(&quot;VfpClientAlias&quot;)
        ///SELECT curTables
        ///SCAN
        ///	SELECT 0
        ///	USE (curTables.TableName) AGAIN ALIAS VfpClientAlias
        ///	
        ///	INSERT INTO curOutput ;
        ///		VALUES(curTables.TableName, ;
        ///			DBGETPROP(curTables.TableName, &quot;TABLE&quot;, &quot;Comment&quot;), ;
        ///			DBGETPROP(curTables.T [rest of string was truncated]&quot;;.
        /// </summary>
        public static string TableProps {
            get {
                return ResourceManager.GetString("TableProps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid quote prefix..
        /// </summary>
        public static string VfpCommandBuilder_InvalidQuotePrefix {
            get {
                return ResourceManager.GetString("VfpCommandBuilder_InvalidQuotePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid quote suffix..
        /// </summary>
        public static string VfpCommandBuilder_InvalidQuoteSuffix {
            get {
                return ResourceManager.GetString("VfpCommandBuilder_InvalidQuoteSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot change a connection string while still connected!.
        /// </summary>
        public static string VfpConnection_CannotChangeConnectionString {
            get {
                return ResourceManager.GetString("VfpConnection_CannotChangeConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot change database when connection is closed!.
        /// </summary>
        public static string VfpConnection_CannotChangeDatabase {
            get {
                return ResourceManager.GetString("VfpConnection_CannotChangeDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More restrictions were provided than the requested schema &apos;{0}&apos; supports..
        /// </summary>
        public static string VfpConnection_GetSchemaTooManyRestrictions {
            get {
                return ResourceManager.GetString("VfpConnection_GetSchemaTooManyRestrictions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The collection &apos;{0}&apos; is unknown..
        /// </summary>
        public static string VfpConnection_GetSchemaUnknownCollection {
            get {
                return ResourceManager.GetString("VfpConnection_GetSchemaUnknownCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The collection &apos;{0}&apos; has {1} restrictions..
        /// </summary>
        public static string VfpConnection_GetSchemaWrongRestrictions {
            get {
                return ResourceManager.GetString("VfpConnection_GetSchemaWrongRestrictions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must open connection before calling GetSchema!.
        /// </summary>
        public static string VfpConnection_OpenConnectionForGetSchema {
            get {
                return ResourceManager.GetString("VfpConnection_OpenConnectionForGetSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE CURSOR curOutput(ViewName v(254), FieldName v(254), Caption M, Comment M, DefaultValue M, DisplayClass M, DisplayClassLibrary M, ;
        ///						Format M, InputMask M, RuleExpression M, RuleText M, KeyField L, Updatable L, UpdateName M, DataType M, FieldType C)
        ///
        ///IF EMPTY(DBC())
        ///	RETURN
        ///ENDIF 
        ///
        ///CREATE CURSOR curViews(ViewName v(254))
        ///{0}
        ///
        ///USE IN SELECT(&quot;VfpClientAlias&quot;)
        ///SELECT curViews
        ///SCAN
        ///	SELECT 0
        ///	USE (curViews.ViewName) AGAIN ALIAS VfpClientAlias NODATA
        ///	
        ///	FOR lnIndex = 1 TO AFIELDS(laFie [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ViewFieldProps {
            get {
                return ResourceManager.GetString("ViewFieldProps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE CURSOR curOutput(ViewName v(254), AllowSimultaneousFetch L, BatchUpdateCount N(19, 0), Comment M, CompareMemo L, ConnectName M, ;
        ///						FetchAsNeeded L, FetchMemo L, FetchSize N(19, 0), MaxRecords N(19, 0), Offline L, ParameterList M, Prepared L, ;
        ///						RuleExpression M, RuleText M, SendUpdates L, ShareConnection L, SourceType N(19, 0), SQL M, Tables M, ;
        ///						UpdateType N(19, 0), UseMemoSize N(19, 0), WhereType N(19, 0))
        ///
        ///IF EMPTY(DBC())
        ///	RETURN
        ///ENDIF 
        ///
        ///CREATE CURSOR curViews(ViewName v(2 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ViewProps {
            get {
                return ResourceManager.GetString("ViewProps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USE IN SELECT (&quot;{0}&quot;)
        ///USE {0} IN SELECT (0) EXCLUSIVE
        ///PACK
        ///USE IN SELECT (&quot;{0}&quot;).
        /// </summary>
        public static string ZapTable {
            get {
                return ResourceManager.GetString("ZapTable", resourceCulture);
            }
        }
    }
}
