// <auto-generated />

namespace VfpClient.Design.ConnectionUI {
    partial class VfpConnectionUIControl {
        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing) {
            if (disposing && (components != null)) {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent() {
            fileNameTableLayoutPanel = new System.Windows.Forms.TableLayoutPanel();
            fileNameTextBox = new System.Windows.Forms.TextBox();
            browseButton = new System.Windows.Forms.Button();
            dataSourceLabel = new System.Windows.Forms.Label();
            fileNameTableLayoutPanel.SuspendLayout();
            SuspendLayout();
            // 
            // fileNameTableLayoutPanel
            // 
            fileNameTableLayoutPanel.AutoSize = true;
            fileNameTableLayoutPanel.ColumnCount = 2;
            fileNameTableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle());
            fileNameTableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle());
            fileNameTableLayoutPanel.Controls.Add(fileNameTextBox, 0, 0);
            fileNameTableLayoutPanel.Controls.Add(browseButton, 1, 0);
            fileNameTableLayoutPanel.Location = new System.Drawing.Point(3, 3);
            fileNameTableLayoutPanel.Name = "fileNameTableLayoutPanel";
            fileNameTableLayoutPanel.RowCount = 1;
            fileNameTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            fileNameTableLayoutPanel.Size = new System.Drawing.Size(318, 35);
            fileNameTableLayoutPanel.TabIndex = 5;
            // 
            // fileNameTextBox
            // 
            fileNameTextBox.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            fileNameTextBox.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.SuggestAppend;
            fileNameTextBox.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.FileSystem;
            fileNameTextBox.Location = new System.Drawing.Point(0, 5);
            fileNameTextBox.Margin = new System.Windows.Forms.Padding(0, 5, 3, 3);
            fileNameTextBox.Name = "fileNameTextBox";
            fileNameTextBox.Size = new System.Drawing.Size(225, 20);
            fileNameTextBox.TabIndex = 2;
            fileNameTextBox.TextChanged += new System.EventHandler(SetFileName);
            // 
            // browseButton
            // 
            browseButton.Location = new System.Drawing.Point(243, 3);
            browseButton.Margin = new System.Windows.Forms.Padding(15, 3, 0, 3);
            browseButton.Name = "browseButton";
            browseButton.Size = new System.Drawing.Size(75, 25);
            browseButton.TabIndex = 1;
            browseButton.Text = "&Browse...";
            browseButton.UseVisualStyleBackColor = true;
            browseButton.Click += new System.EventHandler(Browse);
            // 
            // dataSourceLabel
            // 
            dataSourceLabel.AutoSize = true;
            dataSourceLabel.Location = new System.Drawing.Point(43, 20);
            dataSourceLabel.Name = "dataSourceLabel";
            dataSourceLabel.Size = new System.Drawing.Size(0, 13);
            dataSourceLabel.TabIndex = 4;
            // 
            // VfpConnectionUIControl
            // 
            AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            Controls.Add(fileNameTableLayoutPanel);
            Controls.Add(dataSourceLabel);
            Name = "VfpConnectionUIControl";
            Size = new System.Drawing.Size(398, 43);
            fileNameTableLayoutPanel.ResumeLayout(false);
            fileNameTableLayoutPanel.PerformLayout();
            ResumeLayout(false);
            PerformLayout();

        }

        #endregion

        private System.Windows.Forms.TableLayoutPanel fileNameTableLayoutPanel;
        private System.Windows.Forms.TextBox fileNameTextBox;
        private System.Windows.Forms.Button browseButton;
        private System.Windows.Forms.Label dataSourceLabel;
    }
}
