//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VfpClient.Design.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VfpClient.Design.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this selection to connect to a Microsoft FoxPro database file using the .NET Framework Data Provider for FoxPro..
        /// </summary>
        public static string DataSource_Description {
            get {
                return ResourceManager.GetString("DataSource_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visual FoxPro Data Client.
        /// </summary>
        public static string DataSource_DisplayName {
            get {
                return ResourceManager.GetString("DataSource_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedures.
        /// </summary>
        public static string DataViewSupport_Procedures {
            get {
                return ResourceManager.GetString("DataViewSupport_Procedures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tables.
        /// </summary>
        public static string DataViewSupport_Tables {
            get {
                return ResourceManager.GetString("DataViewSupport_Tables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Views.
        /// </summary>
        public static string DataViewSupport_Views {
            get {
                return ResourceManager.GetString("DataViewSupport_Views", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this data provider to connect to Visual FoxPro Data..
        /// </summary>
        public static string Provider_Description {
            get {
                return ResourceManager.GetString("Provider_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VFP ADO.Net Provider.
        /// </summary>
        public static string Provider_DisplayName {
            get {
                return ResourceManager.GetString("Provider_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VfpClient.
        /// </summary>
        public static string Provider_ShortDisplayName {
            get {
                return ResourceManager.GetString("Provider_ShortDisplayName", resourceCulture);
            }
        }
    }
}
